common: &common
    access_key_id: AKIAIWWQF5REKTC4ZYGQ
    secret_access_key: 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

development:
    <<: *common
    bucket: request_system_test

test:
    <<: *common
    bucket: request_system_test

production:
    <<: *common
    bucket: request_system_test